# Generated by Django 5.1.7 on 2025-04-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
               
                ('nombre', models.CharField(max_length=250)),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
            ],
        ),
    ]
